name: GitHub Actions Octopus Create Release
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:

env:

steps:
  # ...
  - name: Deploy a release in Octopus Deploy ğŸ™
    uses: OctopusDeploy/create-release-action@v3
    env:
      OCTOPUS_API_KEY: ${{ secrets.API_KEY  }}
      OCTOPUS_URL: ${{ secrets.SERVER }}
      OCTOPUS_SPACE: 'Clare'
    with:
      project: 'GitHub Actions'
      release_number: '1.0.0'
      environments: |
        Dev
        Development
        Test
      variables: |
        Foo: Bar
        Fizz: Buzz
        

