name: GitHub Actions Create Release
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
env:
  OCTOPUS_API_KEY: ${{ secrets.API_KEY  }}
  OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
  OCTOPUS_SPACE: 'Clare'
steps:
  # ...
  - name: Create a release in Octopus Deploy ğŸ™
    uses: OctopusDeploy/create-release-action@v3
    with:
      project: 'GitHub Actions'
        

