name: GitHub Actions Create Release
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - main
jobs:
  GitHub-Actions-Deploy-Release:
    name: GitHub-Actions-Create-Release
    runs-on: ubuntu-latest
env:
  OCTOPUS_API_KEY: ${{ secrets.API_KEY  }}
  OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
  OCTOPUS_SPACE: 'Clare'
steps:
  # ...
  - name: Deploy a release in Octopus Deploy ğŸ™
    uses: OctopusDeploy/deploy-release-action@v3
    with:
      project: 'GitHub Actions'
      release_number: '0.0.1'
      environments: |
        Test

        

